openapi: "3.0.0"
info:
  description: "List of all endpoints of API"
  version: "1.0.0"
  title: "Simple Node API"
servers:
  - url: https://balmung-api.herokuapp.com/api
    description: production server on heroku
  - url: http://localhost:3000/api
    description: local server
tags:
- name: "health"
  description: "information about API health"
- name: "register"
  description: "register a new user in database"
- name: "login"
  description: "authentication endpoint"
paths:
  /health:
    get:
      tags:
      - "health"
      summary: "returns information about API health"
      responses:
        200:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
  /register:
    post:
      tags:
      - "register"
      summary: "register a new user in database"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterParameters"
      responses:
        201:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterSuccess"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterBadRequest"
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /login:
    post:
      tags:
      - "login"
      summary: "authenticate the user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginParameters"
      responses:
        200:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/LoginBadRequest'
                  - $ref: '#/components/schemas/LoginWrongUsername'
          
components:
  schemas:
    Health:
      properties:
        health:
          type: "boolean"
        
    DefaultError:
      properties:
        message:
          type: "string"
          example: "Ocoreu um erro inesperado"
  
    RegisterParameters:
      properties:
        email:
          type: "string"
          example: "email@provider.com"
        name:
          type: "string"
          example: "John Doe"
        password:
          type: "string"
          example: "SecretPassword"
  
    RegisterSuccess:
      properties:
        message:
          type: "string"
          example: "User created"
    
    RegisterBadRequest:
      type: "array"
      items:
        type: "object"
        properties:
          message:
            type: "string"
            example: "Informe um email válido"
          path:
            type: "string"
            example: "body.email"
            
    LoginParameters:
      properties:
        email:
          type: "string"
          example: "email@provider.com"
        password:
          type: "string"
          example: "SecretPassword"
            
    LoginSuccess:
      properties:
        message:
          type: "string"
          example: "Seja bem vindo!"
          
    LoginBadRequest:
      type: "array"
      items:
        type: "object"
        properties:
          message:
            type: "string"
            example: "Informe um email válido"
          path:
            type: "string"
            example: "body.email"
            
    LoginWrongUsername:
      properties:
        message:
          type: "string"
          example: "Usuário ou senha incorretas"