openapi: "3.0.0"
info:
  description: "List of all endpoints of API"
  version: "1.0.0"
  title: "Simple Node API"
servers:
  - url: https://balmung-api.herokuapp.com/api
    description: production server on heroku
  - url: http://localhost:3000/api
    description: local server
paths:
  /health:
    get:
      tags:
      - "health"
      summary: "returns information about API health"
      responses:
        200:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
  /register:
    post:
      tags:
      - "register"
      summary: "register a new user in database"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterParameters"
      responses:
        201:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterSuccess"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterBadRequest"
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /login:
    post:
      tags:
      - "login"
      summary: "authenticate the user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginParameters"
      responses:
        200:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/LoginBadRequest'
                  - $ref: '#/components/schemas/LoginWrongUsername'
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

  /email/confirm:
    get:
      tags:
        - "email"
      summary: "email confirmation endpoint"
      parameters:
        - in: query
          name: token
          schema:
            type: string
      responses:
        200:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmailConfirmationSuccess"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailConfirmationBadRequest'
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    
  /email/resend:
    get:
      tags:
        - "email"
      summary: "email confirmation resend endpoint"
      parameters:
        - in: query
          name: email
          schema:
            type: string
      responses:
        200:
          description: "Success request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmailResendSuccess"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailResendBadRequest'
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
          
components:
  schemas:
    Health:
      properties:
        health:
          type: "boolean"
        
    DefaultError:
      properties:
        message:
          type: "string"
          example: "Ocoreu um erro inesperado"
  
    RegisterParameters:
      properties:
        email:
          type: "string"
          example: "email@provider.com"
        name:
          type: "string"
          example: "John Doe"
        password:
          type: "string"
          example: "SecretPassword"
  
    RegisterSuccess:
      properties:
        message:
          type: "string"
          example: "User created"
    
    RegisterBadRequest:
      properties:
        errors:
          type: "array"
          items:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Informe um email válido"
              path:
                type: "string"
                example: "body.email"
            
    LoginParameters:
      properties:
        email:
          type: "string"
          example: "email@provider.com"
        password:
          type: "string"
          example: "SecretPassword"
            
    LoginSuccess:
      properties:
        message:
          type: "string"
          example: "Seja bem vindo!"
          
    LoginBadRequest:
      properties:
        errors:
          type: "array"
          items:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Informe um email válido"
              path:
                type: "string"
                example: "body.email"
            
    LoginWrongUsername:
      properties:
        message:
          type: "string"
          example: "Usuário ou senha incorretas"

    EmailConfirmationSuccess:
      properties:
        message:
          type: "string"
          example: "O seu email foi verificado"
    
    EmailConfirmationBadRequest:
      properties:
        errors:
          type: "array"
          items:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Token de confirmação inválido ou expirado"
              path:
                type: "string"
                example: "query.token"
                
    EmailResendSuccess:
      properties:
        message:
          type: "string"
          example: "Foi enviado um novo código de confirmação para o seu email"
    
    EmailResendBadRequest:
      properties:
        errors:
          type: "array"
          items:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Informe um email válido"
              path:
                type: "string"
                example: "query.email"